=== UO300798/sew/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, distancia, anchura, fecha, hora_inicio, vueltas, localidad, pais, patrocinador, referencias, galeria, videos, coordenadas, resultado)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>

<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidad CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora_inicio (#PCDATA)>
<!ATTLIST hora_inicio zona CDATA #REQUIRED>

<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!-- Referencias -->
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!-- GalerÃ­a -->
<!ELEMENT galeria (foto+)>
<!ELEMENT foto EMPTY>
<!ATTLIST foto nombre CDATA #REQUIRED>

<!-- Videos -->
<!ELEMENT videos (video+)>
<!ELEMENT video EMPTY>
<!ATTLIST video nombre CDATA #REQUIRED descripcion CDATA #REQUIRED>

<!-- Coordenadas y tramos -->
<!ELEMENT coordenadas (origen, tramos)>

<!ELEMENT origen (latitud, longitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT tramos (tramo+)>

<!ELEMENT tramo (distancia, coordenadas_finales, sector)>
<!ELEMENT coordenadas_finales (latitud, longitud, altitud)>
<!ELEMENT sector EMPTY>
<!ATTLIST sector numero CDATA #REQUIRED>

<!-- Resultado -->
<!ELEMENT resultado (vencedor, clasificacion_mundial)>
<!ELEMENT vencedor (#PCDATA)>
<!ATTLIST vencedor tiempo CDATA #REQUIRED>

<!ELEMENT clasificacion_mundial (puesto+)>
<!ELEMENT puesto (#PCDATA)>
<!ATTLIST puesto numero CDATA #REQUIRED>

=== UO300798/sew/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- <!DOCTYPE circuito SYSTEM "circuito.dtd"> -->

<circuito xmlns="http://www.uniovi.es"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Circuit de Barcelona-Catalunya</nombre>
    <distancia unidad="metros">4657</distancia>
    <anchura unidad="metros">12</anchura>
    <fecha>2025-09-07</fecha>
    <hora_inicio zona="CET">14:00:00</hora_inicio>
    <vueltas>24</vueltas>
    <localidad>Montmeló</localidad>
    <pais>España</pais>
    <patrocinador>Monster Energy</patrocinador>
    <referencias>
        <referencia>“Circuit Catalunya MotoGP 2025” — Racing Circuits.https://www.motogp.com/es/calendar/2025/event/catalunya/a4e866f4-8dfd-44fa-b651-05291983be13?tab=circuit-info</referencia>
        <referencia>“Circuito de Barcelona‑Cataluña” — Wikipedia. https://es.wikipedia.org/wiki/Gran_Premio_de_Catalu%C3%B1a_de_Motociclismo</referencia>
        <referencia>“Circuit de Catalunya | MotoGP Barcelona” — página oficial de MotoGP. https://www.motogpbarcelona.com/es/circuito-de-cataluna-1</referencia>
    </referencias>

    <galeria>
        <foto nombre="multimedia/Mapa.jpg"/>
        <foto nombre="multimedia/Tribuna.jpg"/>
        <foto nombre="multimedia/Curva.jpg"/>

    </galeria>

    <videos>
        <video nombre="multimedia/salida.mp4" descripcion="Salida del circuito en el Gran Premio de Catalunya en 2025."/>
    </videos>

    <coordenadas>
    <origen>
        <latitud>41.570031</latitud>
        <longitud>2.261210</longitud>
        <altitud>120</altitud>
    </origen>

    <tramos>
        <tramo>
            <distancia unidad="metros">700</distancia>
            <coordenadas_finales>
                <latitud>41.564702</latitud>
                <longitud>2.256722</longitud>
                <altitud>112</altitud>
            </coordenadas_finales>
            <sector numero="1"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">34</distancia>
            <coordenadas_finales>
                <latitud>41.564629</latitud>
                <longitud>2.256326</longitud>
                <altitud>113</altitud>
            </coordenadas_finales>
            <sector numero="1"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">57</distancia>
            <coordenadas_finales>
                <latitud>41.564872</latitud>
                <longitud>2.255722</longitud>
                <altitud>113</altitud>
            </coordenadas_finales>
            <sector numero="1"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">37</distancia>
            <coordenadas_finales>
                <latitud>41.564871</latitud>
                <longitud>2.255279</longitud>
                <altitud>114</altitud>
            </coordenadas_finales>
            <sector numero="1"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">119</distancia>
            <coordenadas_finales>
                <latitud>41.564273</latitud>
                <longitud>2.254095</longitud>
                <altitud>119</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">57</distancia>
            <coordenadas_finales>
                <latitud>41.564186</latitud>
                <longitud>2.253425</longitud>
                <altitud>122</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">73</distancia>
            <coordenadas_finales>
                <latitud>41.564440</latitud>
                <longitud>2.252611</longitud>
                <altitud>124</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">67</distancia>
            <coordenadas_finales>
                <latitud>41.564963</latitud>
                <longitud>2.252213</longitud>
                <altitud>126</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">76</distancia>
            <coordenadas_finales>
                <latitud>41.565647</latitud>
                <longitud>2.252158</longitud>
                <altitud>127</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>
        <tramo>
            <distancia unidad="metros">57</distancia>
            <coordenadas_finales>
                <latitud>41.566141</latitud>
                <longitud>2.252335</longitud>
                <altitud>128</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">273</distancia>
            <coordenadas_finales>
                <latitud>41.568235</latitud>
                <longitud>2.254052</longitud>
                <altitud>131</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">39</distancia>
            <coordenadas_finales>
                <latitud>41.568425</latitud>
                <longitud>2.254440</longitud>
                <altitud>132</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">37</distancia>
            <coordenadas_finales>
                <latitud>41.568377</latitud>
                <longitud>2.254878</longitud>
                <altitud>132</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">36</distancia>
            <coordenadas_finales>
                <latitud>41.568156</latitud>
                <longitud>2.255202</longitud>
                <altitud>133</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">34</distancia>
            <coordenadas_finales>
                <latitud>41.567870</latitud>
                <longitud>2.255365</longitud>
                <altitud>133</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">52</distancia>
            <coordenadas_finales>
                <latitud>41.567395</latitud>
                <longitud>2.255340</longitud>
                <altitud>133</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">212</distancia>
            <coordenadas_finales>
                <latitud>41.565751</latitud>
                <longitud>2.254023</longitud>
                <altitud>128</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">24</distancia>
            <coordenadas_finales>
                <latitud>41.565535</latitud>
                <longitud>2.253995</longitud>
                <altitud>127</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">21</distancia>
            <coordenadas_finales>
                <latitud>41.565373</latitud>
                <longitud>2.254130</longitud>
                <altitud>126</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">22</distancia>
            <coordenadas_finales>
                <latitud>41.565304</latitud>
                <longitud>2.254375</longitud>
                <altitud>125</altitud>
            </coordenadas_finales>
            <sector numero="2"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">155</distancia>
            <coordenadas_finales>
                <latitud>41.565833</latitud>
                <longitud>2.256104</longitud>
                <altitud>116</altitud>
            </coordenadas_finales>
            <sector numero="3"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">80</distancia>
            <coordenadas_finales>
                <latitud>41.566265</latitud>
                <longitud>2.256859</longitud>
                <altitud>114</altitud>
            </coordenadas_finales>
            <sector numero="3"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">147</distancia>
            <coordenadas_finales>
                <latitud>41.567381</latitud>
                <longitud>2.257801</longitud>
                <altitud>116</altitud>
            </coordenadas_finales>
            <sector numero="3"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">30</distancia>
            <coordenadas_finales>
                <latitud>41.567634</latitud>
                <longitud>2.257691</longitud>
                <altitud>117</altitud>
            </coordenadas_finales>
            <sector numero="3"/>
        </tramo>

        <tramo>
            <distancia unidad="metros">52</distancia>
            <coordenadas_finales>
                <latitud>41.567895</latitud>
                <longitud>2.257171</longitud>
                <altitud>120</altitud>
            </coordenadas_finales>
            <sector numero="3"/>
        </tramo>

        <tramo>
